package levigibson.fto3phase;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

class Util {

    private static final int[] FACTORIAL = new int[] {1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880, 3628800, 39916800, 479001600};

    private static int[][] Cnk;

    /**
     * n choose k combinatorics function
     * performed with a lookup table
     * @param n integer
     * @param k integer
     * @return n choose k
     */
    public static int nCr(int n, int k) {
        return Cnk[n][k];
    }

    /**
     * Swap two elements of an int[] array
     * @param arr array
     * @param i1 index 1
     * @param i2 index 2
     */
    public static void swap(int[] arr, int i1, int i2){
        int tmp = arr[i2];
        arr[i2] = arr[i1];
        arr[i1] = tmp;
    }

    /**
     * Computes the parity of a permutation
     * @param perm shuffle of {0, 1, 2, 3 ...}
     * @return 0 or 1
     */
    public static boolean isParity(int[] perm) {
        perm = Arrays.copyOf(perm, perm.length);

        int n = perm.length;
        int swaps = 0;
        for (int i = 0; i < n; i++) {
            while (perm[i] != i) {
                int target = perm[i];
                swap(perm, i, target);
                swaps++;
            }
        }
        return swaps % 2 == 1;
    }

    /**
     * Computes the parity of a permutation
     * @param perm shuffle of {0, 1, 2, 3 ...}
     * @return 0 or 1
     */
    public static boolean isParity(int perm, int length) {

        int swaps = 0;
        for (int i = 0; i < length; i++) {
            while (((perm >> (4 * i)) & 0b1111) != i) {
                int target = ((perm >> (4 * i)) & 0b1111);
                perm = swapNibbles(perm, i, target);
                swaps++;
            }
        }
        return swaps % 2 == 1;
    }

    /**
     * Pack the permutation of an array into a single integer
     * This creates a bijection!
     * <a href="https://medium.com/@benjamin.botto/sequentially-indexing-permutations-a-linear-algorithm-for-computing-lexicographic-rank-a22220ffd6e3">Link to article explaining the algorithm</a>
     * Invert this function with unpackPerm.
     * @param arr shuffle of {0, 1, 2, 3 ...}
     * @param parity Does this array have a parity constraint?
     * @return Lehmer index
     */
    public static int packPerm(int[] arr, boolean parity){
        return packPerm(arr, parity, arr.length);
    }

    /**
     * Pack the permutation of an array into a single integer
     * This creates a bijection!
     * <a href="https://medium.com/@benjamin.botto/sequentially-indexing-permutations-a-linear-algorithm-for-computing-lexicographic-rank-a22220ffd6e3">Link to article explaining the algorithm</a>
     * Invert this function with unpackPerm.
     * @param arr shuffle of {0, 1, 2, 3 ...}
     * @param parity Does this array have a parity constraint?
     * @param size Override the size of the array with a custom size
     * @return Lehmer index
     */
    public static int packPerm(int[] arr, boolean parity, int size) {
        int index = 0;
        int seen = 0;

        for (int i = 0; i < size; i++) {
            int e = arr[i];
            seen |= (1 << ((size-1) - e));

            int lehmerDigit = e - Integer.bitCount(seen >> (size - e));
            index += Util.FACTORIAL[(size-1)-i] * lehmerDigit;
        }

        return parity ? index / 2 : index;
    }

    /**
     * Unpack a permutation index into an array.
     * This permutation index should be generated with packPerm
     * @param arr array pointer
     * @param idx index generated by packPerm
     * @param parity does this permutation have a parity constraint?
     */
    public static void unpackPerm(int[] arr, int idx, boolean parity) {
        unpackPerm(arr, idx, arr.length, parity);
    }

    /**
     * Unpack a permutation index into an array.
     * This permutation index should be generated with packPerm
     * @param arr array pointer
     * @param idx index generated by packPerm
     * @param size Override the size of the array with a custom size
     * @param parity does this permutation have a parity constraint?
     */
    public static void unpackPerm(int[] arr, int idx, int size, boolean parity){
        if (parity)
            idx *= 2;

        boolean[] used = new boolean[size];
        for (int i = 0; i < size; i++) {
            int lehmerDigit = idx / Util.FACTORIAL[(size-1) - i];
            idx %= Util.FACTORIAL[(size-1) - i];

            int count = 0;
            int e = -1;
            for (int v = 0; v < size; v++) {
                if (!used[v]) {
                    if (count == lehmerDigit) {
                        e = v;
                        break;
                    }
                    count++;
                }
            }

            arr[i] = e;
            used[e] = true;
        }

        if (parity && Util.isParity(arr)){
            Util.swap(arr, size-2, size-1);
        }
    }

    /**
     * Pack a subset of an array
     * Example:
     * The indices of the D centers are at positions 1, 4, and 7 -> bijection
     * Invert this function with unpackSubset
     *      * {@snippet :
     *      *      //Pack a subset
     *      *      int[] indices = {1, 2, 7};
     *      *      int packedIndices = packSubset(indices);
     *      *
     *      *     //Unpack the subset
     *      *      int[] unpackedIndices = new int[3];
     *      *      unpackSubset(unpackedIndices, packedIndices);
     *      *      //unpackedIndices -> {1,2,7}
     *      * }
     *
     * @param idx indices in-order. ex: {1,4,7}
     * @return integer code
     */
    public static int packSubset(int[] idx){
        for (int i = 0; i < idx.length-1; i++) {
            if (idx[i] >= idx[i+1]){
                throw new IllegalArgumentException("idx must be in ascending order");
            }
        }

        int index = 0;
        for (int i = idx.length-1; i >= 0; i--) {
            index += nCr(idx[i], i+1);
        }
        return index;
    }

    private static int swapNibbles(int x, int i0, int i1){
        int n0 = (x >> (4 * i0)) & 0b1111;
        int n1 = (x >> (4 * i1)) & 0b1111;

        int mask = ~((0b1111 << (4 * i0)) | (0b1111 << (4 * i1)));
        x &= mask;
        x |= n0 << (4 * i1);
        x |= n1 << (4 * i0);

        return x;
    }

    public static int packSubset(int packedArr, int length){
        int mask = 0b1111;

        for (int i = 0; i < length-1; i++) {
            if (((packedArr >> (4 * i)) & mask) >=
                ((packedArr >> (4 * (i+1))) & mask)){
                throw new IllegalArgumentException("idx must be in ascending order");
            }
        }

        int index = 0;
        for (int i = length-1; i >= 0; i--) {
            index += nCr(((packedArr >> (4 * i)) & mask), i+1);
        }
        return index;
    }

    /**
     * Turn a packed subset index back into the indices!
     * {@snippet :
     *      //Pack a subset
     *      int[] indices = {1, 2, 7};
     *      int packedIndices = packSubset(indices);
     *
     *     //Unpack the subset
     *      int[] unpackedIndices = new int[3];
     *      unpackSubset(unpackedIndices, packedIndices);
     *      //unpackedIndices -> {1,2,7}
     * }
     *
     * @param arr
     * @param idx
     */
    public static void unpackSubset(int[] arr, int idx){
        int subsetSize = arr.length;

        int k = subsetSize;
        int remaining = idx;

        for (int pos = 0; pos < subsetSize; pos++) {
            int c = k - 1;
            while (nCr(c + 1, k) <= remaining) {
                c++;
            }
            arr[subsetSize - 1 - pos] = c;
            remaining -= nCr(c, k);
            k--;
        }
    }

    private static final Map<String, Integer> MOVE_MAP = new HashMap<>();
    static {
        String[] names = {"R", "L", "B", "U", "D", "F", "BR", "BL"};
        int[] cw  = {FtoCubie.R,  FtoCubie.L,  FtoCubie.B,  FtoCubie.U,
            FtoCubie.D,  FtoCubie.F,  FtoCubie.BR, FtoCubie.BL};
        int[] ccw = {FtoCubie.RP, FtoCubie.LP, FtoCubie.BP, FtoCubie.UP,
            FtoCubie.DP, FtoCubie.FP, FtoCubie.BRP, FtoCubie.BLP};
        for (int i = 0; i < 8; i++) {
            MOVE_MAP.put(names[i], cw[i]);
            MOVE_MAP.put(names[i] + "'", ccw[i]);
        }
    }

    private static int parseMove(String s) {
        Integer move = MOVE_MAP.get(s);
        if (move == null) {
            throw new IllegalArgumentException("Unrecognized move: " + s);
        }
        return move;
    }

    /**
     * Get an FtoCubie object from a string of moves
     * @param alg move string
     * @return FtoCubie
     */
    public static FtoCubie applyAlg(String alg) {
        FtoCubie a = new FtoCubie();   // solved state
        FtoCubie b = new FtoCubie();   // temp buffer
        for (String token : alg.trim().split("\\s+")) {
            a.turn(parseMove(token), b);
            FtoCubie tmp = a;
            a = b;
            b = tmp;
        }
        return a;
    }

    private static final String[] INVERSE_MOVE_NAMES = {"R'", "R", "L'", "L", "B'", "B", "U'", "U", "D'", "D", "F'", "F", "BR'", "BR", "BL'", "BL"};

    /**
     * Turns an array of moves into a human-readable scramble
     * This function also inverts the moves because that's
     * required for a random state scrambler.
     * @param moves array of moves
     * @return human-readable string
     */
    public static String moveArrayToInvertedString(int[] moves) {

        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < moves.length; i++) {
            if (i > 0) {
                sb.append(' ');
            }
            sb.append(INVERSE_MOVE_NAMES[moves[moves.length - 1 - i]]);
        }
        return sb.toString();
    }

    /**
     * Raise `a` to the power of `b`
     * @param a number
     * @param b number
     * @return a ^ b
     */
    public static int pow(int a, int b){
        int c = 1;
        for (int i = 0; i < b; i++) {
            c *= a;
        }
        return c;
    }

    private static int choose(int n, int k){
        if (k < 0 || k > n) return 0;
        if (k == 0 || k == n) return 1;
        if (k > n - k) k = n - k;

        long result = 1;
        for (int i = 1; i <= k; i++) {
            result = result * (n - k + i) / i;
        }
        assert result <= Integer.MAX_VALUE
            : "choose(" + n + ", " + k + ") = " + result + " overflows int";
        return (int) result;
    }

    private static void computeChooseTable(){
        Cnk = new int[13][13];

        for (int n = 0; n < 13; n++) {
            for (int k = 0; k < 13; k++) {
                Cnk[n][k] = choose(n, k);
            }
        }
    }

    static {computeChooseTable();}
}
